"""alter_table_add_status_change_at_on_event_table

Revision ID: 199b40c274e7
Revises: f391490d3fa9
Create Date: 2023-08-26 18:08:17.283643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199b40c274e7'
down_revision = 'f391490d3fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_change_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('status_change_at')

    # ### end Alembic commands ###
