"""alter_table_add_ondelte_cascade_for_event_ticket_table

Revision ID: 21069897ab61
Revises: 199b40c274e7
Create Date: 2023-08-26 18:39:02.825930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21069897ab61'
down_revision = '199b40c274e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('tickets_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['event_id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['ticket_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_ibfk_1', 'tickets', ['ticket_id'], ['ticket_id'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tickets_ibfk_1', 'events', ['event_id'], ['event_id'])

    # ### end Alembic commands ###
