"""Create_Ticket_table

Revision ID: 734664dd0b82
Revises: c6f3e7ccf086
Create Date: 2023-08-21 16:05:02.108956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734664dd0b82'
down_revision = 'c6f3e7ccf086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_code', sa.String(length=6), nullable=True),
    sa.Column('is_attended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATE(), nullable=True))

    op.drop_table('tickets')
    # ### end Alembic commands ###
